name: jaguar_gen_negtests
description: A starting point for Dart libraries or applications.
version: 0.0.1
#author: Ravi Teja Gudapati <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  jaguar_generator:
    path: ../jaguar_generator
    # git: https://github.com/Jaguar-dart/jaguar_generator.git

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
